const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.TileMovement,
		C3.Behaviors.Timer,
		C3.Behaviors.solid,
		C3.Behaviors.LOS,
		C3.Behaviors.MoveTo,
		C3.Plugins.Keyboard,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Plugins.SpeechSynthesis,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.TileMovement.Cnds.IsMovingDirection,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.TileMovement.Cnds.IsMoving,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.TileMovement.Acts.SetEnabled,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.SpeechSynthesis.Acts.SpeakText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset
	];
};
self.C3_JsPropNameTable = [
	{Tilemap_base: 0},
	{ScrollTo: 0},
	{TileMovement: 0},
	{Timer: 0},
	{player: 0},
	{Solid: 0},
	{Tilemap_solid: 0},
	{LineOfSight: 0},
	{MoveTo: 0},
	{enemy: 0},
	{Keyboard: 0},
	{Pin: 0},
	{sword: 0},
	{chest_sword_store: 0},
	{chest_zone: 0},
	{Gui_Modol: 0},
	{GUI_content: 0},
	{GUI_Enter: 0},
	{message_box: 0},
	{score: 0},
	{coin: 0},
	{SpeechSynthesis: 0},
	{complete: 0},
	{stand: 0},
	{CoinScore: 0},
	{Tilemap: 0},
	{Tilemap_level2_base: 0},
	{Tilemap_level2_solid: 0},
	{winner: 0},
	{Text: 0},
	{Audio: 0},
	{direction: 0},
	{Attack: 0},
	{dead: 0},
	{Got_Sword: 0},
	{message_shown: 0},
	{coinscore: 0}
];

self.InstanceType = {
	Tilemap_base: class extends self.ITilemapInstance {},
	player: class extends self.ISpriteInstance {},
	Tilemap_solid: class extends self.ITilemapInstance {},
	enemy: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	sword: class extends self.ISpriteInstance {},
	chest_sword_store: class extends self.ISpriteInstance {},
	chest_zone: class extends self.ISpriteInstance {},
	Gui_Modol: class extends self.ISpriteInstance {},
	GUI_content: class extends self.ITextInstance {},
	GUI_Enter: class extends self.ITextInstance {},
	message_box: class extends self.ISpriteInstance {},
	score: class extends self.ITextInstance {},
	coin: class extends self.ISpriteInstance {},
	SpeechSynthesis: class extends self.IInstance {},
	complete: class extends self.ISpriteInstance {},
	stand: class extends self.ISpriteInstance {},
	CoinScore: class extends self.ITextInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Tilemap_level2_base: class extends self.ITilemapInstance {},
	Tilemap_level2_solid: class extends self.ITilemapInstance {},
	winner: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {}
}